<a href="https://colab.research.google.com/github/Hesenius/Applying-Math-with-Python/blob/master/Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1,2,7],[-1,0,1],[2,1,3]])

B = np.array([[3,1,8],[-2,0,-1],[-2,-5,0]])

AB = np.matmul(A,B)
print(AB)


[[-15 -34   6]
 [ -5  -6  -8]
 [ -2 -13  15]]


In [ ]:
# Where do these numbers come from?

# Pick a row and column for the new matrix AB.

row = 2
column = 1

# Multiply this row from A and the column from B.

RowColumn = A[row,:]*B[:,column]

print(A[row,:])
print(B[:,column])

print(RowColumn)

print(sum(RowColumn))

[2 1 3]
[ 1  0 -5]
[  2   0 -15]
-13


In [ ]:
# Does it work in reverse?

# Pick a row and column for the new matrix AB.

row = 2
column = 0

# Multiply this row from A and the column from B.

print('=== A times B ===')

RowColumn = A[row,:]*B[:,column]

print(RowColumn)

print(sum(RowColumn))

# Multiply this row from B and the column from A.

print('=== B times A ===')

RowColumn = B[row,:]*A[:,column]

print(RowColumn)

print(sum(RowColumn))

=== A times B ===
[ 6 -2 -6]
-2
=== B times A ===
[-2  5  0]
3


In [ ]:
print(np.matmul(A,B))
print(np.matmul(B,A))

[[-15 -34   6]
 [ -5  -6  -8]
 [ -2 -13  15]]
[[ 18  14  46]
 [ -4  -5 -17]
 [  3  -4 -19]]


In [ ]:
# Now apply to Lorentz Transformations!

import numpy as np

def lorentz(v):
  c = 1 # God-given units
  beta  = v/c
  gamma = (1-beta**2)**-0.5

  return np.array([
    [gamma,-beta*gamma,0,0],
    [-beta*gamma,gamma,0,0],
    [0,0,1,0],
    [0,0,0,1]
  ])

v = 0.5

print(lorentz(v))

x = np.array([[np.pi],[np.exp(2)],[0],[0]])
print(x)
print(np.matmul(lorentz(v),x))

# What if you needed to apply lorentz twice?
print(np.matmul(lorentz(v/2),np.matmul(lorentz(v),x)))

# In reverse?
print('=== reverse! ===')
print(np.matmul(lorentz(v/2),x))
print(np.matmul(lorentz(v),np.matmul(lorentz(v/2),x)))


[[ 1.15470054 -0.57735027  0.          0.        ]
 [-0.57735027  1.15470054  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[3.14159265]
 [7.3890561 ]
 [0.        ]
 [0.        ]]
[[-0.6384748 ]
 [ 6.71834769]
 [ 0.        ]
 [ 0.        ]]
[[-2.39408385]
 [ 7.10353314]
 [ 0.        ]
 [ 0.        ]]
=== reverse! ===
[[1.33677686]
 [6.82022859]
 [0.        ]
 [0.        ]]
[[-2.39408385]
 [ 7.10353314]
 [ 0.        ]
 [ 0.        ]]
